### ISSUE TITLE
A space character in the Primary Component Name breaks the Graph

### ISSUE THREAD

**Issue by audra-hatch** [CERTCC/SBOM#1]
Issue: Including a space character in the Primary Component Name breaks the Graph from displaying any Included components.  

Note: Including a space character in an Included Component Name _does not_ break the graph from displaying further Included components.

**Comment by sei-vsarvepalli** [comment]
Thanks Audie

Should be a simple fix. Will push it out the fix tonight sometime.

**Comment by sei-vsarvepalli** [comment]
Resolved now.  I will wait for users to confirm, then can close it.

**Comment by sei-vsarvepalli** [comment]
Time to close one thing least this week.
