### ISSUE TITLE
NPM packages failed to Import

### ISSUE THREAD

**Issue by phanisrirs8** [CERTCC/SBOM#12]
When I tried to import the NPM packages like Jasmine, I am getting the error like this:

![2021-10-21 (2)](https://user-images.githubusercontent.com/66828448/138232439-dacfe7bf-f5b9-466b-a6e8-e9e1b2dc6044.png)

Please guide me to how to solve this issue.

**Comment by sei-vsarvepalli** [comment]
Hello  @phanisrirs8 

Looks like npms.io API is down at the moment. I will try to ping them about the issue.

Thanks
Vijay

**Comment by phanisrirs8** [comment]
Hello @sei-vsarvepalli 

Thankyou for your Response.
The tool is working now.
