### ISSUE TITLE
How to work on CycloneDX in this tool

### ISSUE THREAD

**Issue by phanisrirs8** [CERTCC/SBOM#13]
Hi @sei-vsarvepalli 

I have understood how to work on this tool to Import SPDX, Excel, NPM and PIP packages. But I am not understanding how can I work on CycloneDX in this tool. Is it possible to import or any other way to add XML/JSON file into CycloneDX?

Please guide me.

**Comment by sei-vsarvepalli** [comment]
Hi there,

In this project, we started with SPDX as the primary format (or core format) and mapped all the content to equivalent fields in CycloneDX.  So natively the support of CylconeDX is limited.  There is no real import of CylconeDX currently.  Have you looked at https://cyclonedx.org/tool-center/ for CycloneDX tools.  

Thanks
Vijay

**Comment by phanisrirs8** [comment]
Hello @sei-vsarvepalli 

Thank you for your response.
