### ISSUE TITLE
SPDX versions

### ISSUE THREAD

**Issue by Yayoo19** [CERTCC/SBOM#15]
Hi @sei-vsarvepalli,

I would like to know which versions of SPDX does the tooling support?

**Comment by sei-vsarvepalli** [comment]
Hello @Yayoo19 

Sorry if the website is not obvious. It should show the sample document with SPDXVersion: SPDX-2.1, so far we have been supporting spec 2.1.  Is there an interest for various versions?

Thanks
vijay
