### ISSUE TITLE
Better post meeting communication

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [CERTCC/SBOM#7]
Suggest that this repo enables the new discussion features and creates a Gitter so that post meeting conversations amongst the community can continue

**Comment by sei-vsarvepalli** [comment]
Hello @its-a-lisa-at-work 

Thanks for your feedback.

I have to look into details of enabling these features.  This repository is part of a corporate repository where I don't see the discussions features options enabled.  It may take some time to check with our organization Git account owner to find out what is needed to enable this.


Vijay

**Comment by sei-vsarvepalli** [comment]
Sorry for the delay in this .  I have finally made a connection to a Gitter Community calling it SwiftBOM, you have been invited. 
https://gitter.im/SwiftBOM/community

**Comment by sei-vsarvepalli** [comment]
This gutter community is active now.
