### ISSUE TITLE
Import Excel Template Not Working

### ISSUE THREAD

**Issue by audra-hatch** [CERTCC/SBOM#8]
The "Import Excel Template" option isn't importing information.  It successfully prompts to select a file and provides the "Experimental!" warning, but information does not populate in the fields for the document or component information.

**Comment by sei-vsarvepalli** [comment]
Hi Audie,

Thanks for reporting this. 

There is a compatibility issue with the new JSZIP library.  I will update it in development and merge it later after testing.  This way we a proper SBOM for the tool itself.

Vijay

**Comment by sei-vsarvepalli** [comment]
Just pushed a development branch to the website.  @audra-hatch Please try it again and let me know.  Make sure your browser cache is clear. You could just restart the browser to be safe.

Thanks
Vijay

**Comment by audra-hatch** [comment]
It works!  Tested in Chrome and Safari.  Thank you!

**Comment by sei-vsarvepalli** [comment]
Resolved with PR #9 , tested with development branch by @audra-hatch 

Vijay
